# Global Configurations

# Name of Website
title: Nancy Wang (汪岚)

# Owner Information
name: Nancy Wang
github: https://github.com/nancy-wang
linkedin: https://www.linkedin.com/in/nancywangjhu/
email: nwang625@gmail.com

# Other configurations
animate-text: false